name: Test

on:
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v1
      - name: Setup node version
        uses: actions/setup-node@v1
        with:
          node-version: "24"

      - run: corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Build typescript
        run: pnpm build

      - name: Unit tests
        run: pnpm test

      - name: Integration tests
        run: yarn test:integration
